# -*- coding: utf-8 -*-
"""Module2Class1_Assignment_FeruzaBonuKhurramova.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tWcFs8b33c4T98LfZ2kAhIV6kzW4f7Hs
"""

print("Hello, AI/ML!")

# coding_inf_about_me
age = 24
name = "Feruzabonu"
surname = "Khurramova"
gpa = 4.91
is_student = False
scores = [96, 99, 95, 98]

print(age, type(age))
print(gpa, type(gpa))
print(name, type(name))
print(is_student, type(is_student))
print(scores, type(scores))

def calculate_average(numbers):
    total = sum(numbers)    # Push this in with Tab
    count = len(numbers)    # Push this in with Tab
    return total / count    # Push this in with Tab

# These lines stay on the left because they are NOT part of the function
test1 = [80, 90, 70, 85, 95]
test2 = [55, 62, 48, 71]
print("Average 1:", calculate_average(test1))
print("Average 2:", calculate_average(test2))

# Example: Using a list of countries
countries = ["Italy", "Paris", "Turkey", "Tokio", "Seul"]
for index, country in enumerate(countries):
    # This line is indented because it is INSIDE the loop
    print(f"Index {index}: {country}")

import random

# 1. Create the scores
exam_scores = [random.randint(0, 100) for _ in range(10)]
print("Scores:", exam_scores)

# 2. Calculate the average using your Task 3 function
avg = calculate_average(exam_scores)
print(f"Class average: {avg:.1f}")

# 3. Decision logic
if avg >= 60:
    print("Result: PASS")
else:
    print("Result: FAIL")